Checks for strtol_l function
strtol_l (and strtoul_l, strtoll_l, strtoull_l) are not always available
(for example on musl) so check for strtol_l and reuse android fallback if
needed to avoid the following build failure:

/home/buildroot/autobuild/instance-1/output-1/build/ogre-1.12.0/OgreMain/src/OgreStringConverter.cpp: In static member function 'static bool Ogre::StringConverter::parse(const String&, Ogre::int32&)':
/home/buildroot/autobuild/instance-1/output-1/build/ogre-1.12.0/OgreMain/src/OgreStringConverter.cpp:253:22: error: 'strtol_l' was not declared in this scope
         ret = (int32)strtol_l(val.c_str(), &end, 0, _numLocale);
                      ^~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/107cffe41081ce46441dec8699d6ad0f152bc152

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>